name: Tests and Style

on:
  push:
    branches:
      - '*'
      - !master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v1
      with:
        php-version: '7.2'
        extensions: openssl
        tools: composer

    - name: Get Composer Cache Directory
      id: composer-cache
      run: echo "::set-output name=dir::$(composer config cache-files-dir)"

    - name: Load Composer Cache
      uses: actions/cache@v1
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer
        restore-keys: |
          ${{ runner.os }}-composer

    - name: Install Dependencies
      run: composer install --prefer-dist

    - name: Test Code Style
      run: composer test:style

    - name: Test Units
      run: composer test:unit